language: python
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
python:
- '2.7'
script:
- echo "skip pytest";
before_install:
- echo "installing dependencies";
after_script:
- if [ "master" == "$TRAVIS_BRANCH" ] && [ "$TRAVIS_EVENT_TYPE" == "push" ]; then
    echo "Deploying to GCS";
  else
    echo "$TRAVIS_BRANCH";
    echo "$TRAVIS_EVENT_TYPE"; 
    echo "No GCS deployment because build was not triggered by push to master";
  fi 
deploy:
  provider: script
  script: chmod +x ./deploy.sh && ./deploy.sh 
  on:
    branch: master